# PauseScreenPing's Config

# Display Name or Title on the Pause Menu
# If you want it to be empty, just do " "
display-name: "&dPauseScreenPing"

# Update the ping of the players every x ticks
# (20 ticks = 1 second) 
# Allowed values: Integer (1 or more)
update-interval: 20

# Only see own ping (true/false)
only-see-own-ping: false
